### ISSUE TITLE
cant install on vscode

### ISSUE THREAD

**Issue by zernonia** [cpreston321/nuxt-vscode#1]
Seems like vscode doesn't allow downloading pre-release extension

![image](https://user-images.githubusercontent.com/59365435/191408989-d8835619-cdbc-44f5-b0a1-dd9273cff698.png)

**Comment by cpreston321** [comment]
It's in Pre-release so you have to click dropdown.

<img width="636" alt="image" src="https://user-images.githubusercontent.com/6619884/191409643-e3b11ae7-f633-4dea-b5e9-9f028fa4d800.png">
