### ISSUE TITLE
feat: check for `local nuxi`

### ISSUE THREAD

**Issue by tesla3327** [cpreston321/nuxt-vscode#2]
The docs show to use `nuxi` via `npx`/`pnpm dlx`, but I found that was quite slow, so I ended up installing it locally.

If we could somehow prioritize using a local version of `nuxi` it would make this command much faster.

A few ideas:
1. Look for `nuxi` first and only use `npx` if not found
2. Make the `nuxi` command configurable
3. Automatically install `nuxi` locally to speed up the extension

**Comment by cpreston321** [comment]
@tesla3327  Great Ideas I will work on this within the next pre-release version. 

As for the for `2` can you go into more detail ? 

Thanks!
