### ISSUE TITLE
Suggestion: Auto detect file extension and slice it off

### ISSUE THREAD

**Issue by zernonia** [cpreston321/nuxt-vscode#5]
When using `Nuxt: Add Component`, sometimes I accidentally key in `Test.vue`, instead `Test` for the component name, thus generating a component named `Test.vue.vue`.
It would be great if the extension auto detect and slice off `.vue` extension. 

It could also be extended to creating composables (auto detect `.ts`)

😁

**Comment by cpreston321** [comment]
This sounds reasonable. I will work on this!
