### ISSUE TITLE
[SUGGESTION] run the postinstall(`nuxtprepare`) command after `Nuxt Utilities Upgrade`

### ISSUE THREAD

**Issue by BayBreezy** [cpreston321/nuxt-vscode#9]
Hey @cpreston321 - Nice package you have here. I was just testing it out and realized that after running the command called `Nuxt Utilities Upgrade` it did not generate the `.nuxt` folder with the types. Maybe you can add the `nuxt prepare` command at the end of this one.

Keep up the good work 👍🏽

**Comment by cpreston321** [comment]
Will look into this, I honestly didn't know if many people used it... so I didn't really didn't much too much work into it. I will definitely update it.

I appreciate your feedback. Means the world -- when I create something people like using. 💚

**Comment by BayBreezy** [comment]
This is actually good lol. I'm gonna promote it in my next video and on Twitter 

I love that you can create the stuff by clicking on the folder in vscode.

Thanks 😊 again

**Comment by cpreston321** [comment]
@BayBreezy Should be good to go. I also added a setting within vscode so if you want to disable the run prepare after upgrade you can! 

Thanks again for all the support. 💚
